version: '3'
services:
  api:
    container_name: api_service
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - docker-network

networks:
  docker-network:

volumes:
  api_db_data:
